import json

shot_analyses = [
    {"shot_index": 0, "start_time": 0.0, "end_time": 1.0, "has_face": False,
     "content": {"main_subject": "机场候机大厅全景，手持车票", "people_count": 0, "people_description": "", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工冷白光，明亮", "has_text_in_frame": True, "text_content": "登机牌信息"},
     "technique": {"shot_size": "medium", "composition": "第一人称手持视角", "camera_movement": "手持轻微晃动", "visual_quality": "高清干净"},
     "structure_role": {"primary_function": "hook", "confidence": 0.9, "reasoning": "手持车票+机场环境，制造即将出发的期待感和悬念"},
     "emotion": "期待", "one_sentence_summary": "机场手持车票，旅行即将开始的期待感hook"},
    {"shot_index": 1, "start_time": 1.0, "end_time": 2.0, "has_face": False,
     "content": {"main_subject": "机场大厅，车票特写", "people_count": 0, "people_description": "", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工冷白光", "has_text_in_frame": True, "text_content": "车票信息"},
     "technique": {"shot_size": "close_up", "composition": "前景特写", "camera_movement": "手持", "visual_quality": "有轻微动态模糊"},
     "structure_role": {"primary_function": "hook", "confidence": 0.85, "reasoning": "车票特写强化目的地信息，延续开头的期待情绪"},
     "emotion": "期待", "one_sentence_summary": "车票特写，强化出行主题"},
    {"shot_index": 2, "start_time": 2.0, "end_time": 3.0, "has_face": False,
     "content": {"main_subject": "机场标识牌/环境", "people_count": 0, "people_description": "", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工光", "has_text_in_frame": True, "text_content": "登机口信息"},
     "technique": {"shot_size": "medium", "composition": "环境展示", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "scene_establish", "confidence": 0.8, "reasoning": "展示机场环境，确认出发场景"},
     "emotion": "期待", "one_sentence_summary": "机场环境空镜，场景建立"},
    {"shot_index": 3, "start_time": 3.0, "end_time": 4.0, "has_face": False,
     "content": {"main_subject": "机场自动步道/走廊", "people_count": 1, "people_description": "人物背影", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工顶光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium_long", "composition": "跟随背影", "camera_movement": "跟随", "visual_quality": "高清"},
     "structure_role": {"primary_function": "scene_establish", "confidence": 0.75, "reasoning": "行走背影过渡，从出发到抵达的叙事推进"},
     "emotion": "期待", "one_sentence_summary": "机场步道行走背影，过渡感"},
    {"shot_index": 4, "start_time": 4.0, "end_time": 5.0, "has_face": False,
     "content": {"main_subject": "机场到达大厅", "people_count": 0, "people_description": "", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "环境展示", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "scene_establish", "confidence": 0.7, "reasoning": "到达场景的空镜过渡"},
     "emotion": "平静", "one_sentence_summary": "到达大厅环境"},
    {"shot_index": 5, "start_time": 5.0, "end_time": 6.0, "has_face": True,
     "content": {"main_subject": "机场自动步道，人物背影，大字四月重庆文字卡", "people_count": 2, "people_description": "两人背影，一男一女，背背包", "scene_type": "机场", "indoor_outdoor": "indoor", "color_temperature": "cool", "light_quality": "人工顶光", "has_text_in_frame": True, "text_content": "四月 重庆"},
     "technique": {"shot_size": "medium_long", "composition": "居中构图+文字叠加", "camera_movement": "固定", "visual_quality": "高清，设计感文字"},
     "structure_role": {"primary_function": "scene_establish", "confidence": 0.95, "reasoning": "核心文字卡明确时间地点主题，是Vlog的定调镜头"},
     "emotion": "期待", "one_sentence_summary": "四月重庆文字卡，明确旅行主题和目的地"},
    {"shot_index": 6, "start_time": 6.0, "end_time": 7.0, "has_face": False,
     "content": {"main_subject": "重庆标志性黄色出租车队列", "people_count": 0, "people_description": "", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "neutral", "light_quality": "阴天自然光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium_long", "composition": "俯拍对称构图", "camera_movement": "固定", "visual_quality": "高清干净"},
     "structure_role": {"primary_function": "scene_establish", "confidence": 0.9, "reasoning": "重庆黄色法拉利出租车是极具辨识度的城市符号，强力建立重庆场景"},
     "emotion": "活力", "one_sentence_summary": "重庆黄色出租车队列俯拍，标志性城市名片"},
    {"shot_index": 7, "start_time": 7.0, "end_time": 8.0, "has_face": False,
     "content": {"main_subject": "出租车队列近景", "people_count": 0, "people_description": "", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "neutral", "light_quality": "自然光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "俯拍", "camera_movement": "轻微平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.7, "reasoning": "延续出租车场景，展示城市风貌"},
     "emotion": "活力", "one_sentence_summary": "出租车队列近景"},
    {"shot_index": 8, "start_time": 8.0, "end_time": 9.0, "has_face": True,
     "content": {"main_subject": "城市街景，有人物", "people_count": 2, "people_description": "行人背影", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "黄昏/傍晚自然光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "三分法", "camera_movement": "跟随", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.7, "reasoning": "城市街景，展示城市生活节奏"},
     "emotion": "活力", "one_sentence_summary": "城市街道行人日常"},
    {"shot_index": 9, "start_time": 9.0, "end_time": 10.0, "has_face": True,
     "content": {"main_subject": "繁华商业街，密集人群", "people_count": 10, "people_description": "众多行人，年轻人群", "scene_type": "商业街", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚暖光", "has_text_in_frame": True, "text_content": "ONE"},
     "technique": {"shot_size": "medium", "composition": "人群构图", "camera_movement": "跟随/平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.75, "reasoning": "繁华商业街展示城市热闹氛围"},
     "emotion": "欢乐", "one_sentence_summary": "繁华商业街人流，城市活力"},
    {"shot_index": 10, "start_time": 10.0, "end_time": 11.0, "has_face": True,
     "content": {"main_subject": "商业街近景，人群", "people_count": 5, "people_description": "年轻行人，购物人群", "scene_type": "商业街", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚暖光", "has_text_in_frame": True, "text_content": "广告牌文字"},
     "technique": {"shot_size": "medium", "composition": "人群构图", "camera_movement": "手持", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.7, "reasoning": "延续商业街氛围展示"},
     "emotion": "欢乐", "one_sentence_summary": "商业街人群近景"},
    {"shot_index": 11, "start_time": 11.0, "end_time": 12.0, "has_face": True,
     "content": {"main_subject": "商业街人物", "people_count": 3, "people_description": "年轻女性行人", "scene_type": "商业街", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "跟随", "camera_movement": "手持", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.65, "reasoning": "街头日常记录"},
     "emotion": "欢乐", "one_sentence_summary": "商业街行人日常"},
    {"shot_index": 12, "start_time": 12.0, "end_time": 13.0, "has_face": True,
     "content": {"main_subject": "街道/建筑近景", "people_count": 2, "people_description": "行人", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "三分法", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.65, "reasoning": "城市街景展示"},
     "emotion": "活力", "one_sentence_summary": "城市街道建筑"},
    {"shot_index": 13, "start_time": 13.0, "end_time": 14.0, "has_face": False,
     "content": {"main_subject": "街道/店铺", "people_count": 0, "people_description": "", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚", "has_text_in_frame": True, "text_content": "店铺招牌"},
     "technique": {"shot_size": "medium", "composition": "环境展示", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.6, "reasoning": "日常街景记录"},
     "emotion": "活力", "one_sentence_summary": "街道店铺环境"},
    {"shot_index": 14, "start_time": 14.0, "end_time": 15.0, "has_face": True,
     "content": {"main_subject": "城市街道人物", "people_count": 3, "people_description": "行人", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "傍晚", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "跟随", "camera_movement": "手持", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.65, "reasoning": "街头漫步记录"},
     "emotion": "欢乐", "one_sentence_summary": "街头行人漫步"},
    {"shot_index": 15, "start_time": 15.0, "end_time": 16.0, "has_face": False,
     "content": {"main_subject": "城市建筑/街道", "people_count": 0, "people_description": "", "scene_type": "街道", "indoor_outdoor": "outdoor", "color_temperature": "neutral", "light_quality": "傍晚", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium_long", "composition": "环境展示", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "transition", "confidence": 0.7, "reasoning": "从白天街景过渡到夜景的过渡空镜"},
     "emotion": "平静", "one_sentence_summary": "城市建筑过渡镜头"},
    {"shot_index": 16, "start_time": 16.0, "end_time": 17.0, "has_face": False,
     "content": {"main_subject": "城市夜景建筑", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景人工光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "城市大景", "camera_movement": "固定", "visual_quality": "高清，夜景灯光璀璨"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.7, "reasoning": "夜景初现，氛围开始转变"},
     "emotion": "期待", "one_sentence_summary": "城市夜景初现"},
    {"shot_index": 17, "start_time": 17.0, "end_time": 18.0, "has_face": True,
     "content": {"main_subject": "城市夜景，人物", "people_count": 2, "people_description": "人物剪影", "scene_type": "观景台", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景，灯光璀璨", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium", "composition": "框架构图，人物剪影", "camera_movement": "固定", "visual_quality": "高清，有氛围感"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.85, "reasoning": "夜景+人物剪影开始有情绪感染力"},
     "emotion": "温馨", "one_sentence_summary": "夜景人物剪影，情绪开始升温"},
    {"shot_index": 18, "start_time": 18.0, "end_time": 19.0, "has_face": True,
     "content": {"main_subject": "观景台夜景，人物剪影俯瞰城市", "people_count": 2, "people_description": "一男一女剪影，背对镜头", "scene_type": "观景台", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景灯光，有氛围感", "has_text_in_frame": True, "text_content": "云端之眼"},
     "technique": {"shot_size": "medium_long", "composition": "框架构图+对称", "camera_movement": "固定", "visual_quality": "高清，氛围感强"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.95, "reasoning": "经典观景台剪影+来福士背景，是整条Vlog视觉最美、最有感染力的画面，情绪顶点"},
     "emotion": "震撼", "one_sentence_summary": "观景台人物剪影+来福士夜景，情绪高点"},
    {"shot_index": 19, "start_time": 19.0, "end_time": 20.0, "has_face": False,
     "content": {"main_subject": "城市夜景俯瞰", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景灯光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "大全景", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.8, "reasoning": "夜景大全景延续高潮情绪"},
     "emotion": "震撼", "one_sentence_summary": "城市夜景大全景俯瞰"},
    {"shot_index": 20, "start_time": 20.0, "end_time": 21.0, "has_face": False,
     "content": {"main_subject": "洪崖洞夜景（标志性金黄色建筑群）", "people_count": 0, "people_description": "", "scene_type": "景区", "indoor_outdoor": "outdoor", "color_temperature": "warm", "light_quality": "夜景灯光，金黄色", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清，灯光璀璨"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.9, "reasoning": "洪崖洞是重庆最标志性的夜景，金黄色灯光极具视觉冲击力"},
     "emotion": "震撼", "one_sentence_summary": "洪崖洞金黄色夜景，重庆标志性景观"},
    {"shot_index": 21, "start_time": 21.0, "end_time": 22.0, "has_face": True,
     "content": {"main_subject": "长江索道视角，城市景观", "people_count": 1, "people_description": "隐约可见人物", "scene_type": "索道/江景", "indoor_outdoor": "outdoor", "color_temperature": "neutral", "light_quality": "黄昏/夜景过渡", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "框架构图", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.8, "reasoning": "索道视角独特，展示重庆立体城市特征"},
     "emotion": "震撼", "one_sentence_summary": "长江索道视角城市景观"},
    {"shot_index": 22, "start_time": 22.0, "end_time": 23.0, "has_face": True,
     "content": {"main_subject": "江景+城市建筑", "people_count": 2, "people_description": "人物", "scene_type": "江景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "对称构图", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.75, "reasoning": "江景+建筑，延续夜景高潮"},
     "emotion": "震撼", "one_sentence_summary": "江景城市夜景"},
    {"shot_index": 23, "start_time": 23.0, "end_time": 24.0, "has_face": True,
     "content": {"main_subject": "夜景城市", "people_count": 2, "people_description": "人物剪影", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景灯光", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium_long", "composition": "人物+城市", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "emotion_peak", "confidence": 0.8, "reasoning": "人物+夜景，情绪渲染"},
     "emotion": "温馨", "one_sentence_summary": "人物剪影+夜景"},
    {"shot_index": 24, "start_time": 24.0, "end_time": 25.0, "has_face": False,
     "content": {"main_subject": "城市夜景空镜", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "大景", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.6, "reasoning": "夜景空镜过渡"},
     "emotion": "平静", "one_sentence_summary": "夜景空镜过渡"},
    {"shot_index": 25, "start_time": 25.0, "end_time": 26.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "daily_moment", "confidence": 0.6, "reasoning": "夜景展示"},
     "emotion": "平静", "one_sentence_summary": "城市夜景"},
    {"shot_index": 26, "start_time": 26.0, "end_time": 27.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "平移", "visual_quality": "高清"},
     "structure_role": {"primary_function": "transition", "confidence": 0.65, "reasoning": "夜景过渡镜头"},
     "emotion": "平静", "one_sentence_summary": "夜景过渡"},
    {"shot_index": 27, "start_time": 27.0, "end_time": 28.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "transition", "confidence": 0.65, "reasoning": "夜景过渡"},
     "emotion": "平静", "one_sentence_summary": "夜景空镜"},
    {"shot_index": 28, "start_time": 28.0, "end_time": 29.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "transition", "confidence": 0.65, "reasoning": "夜景过渡"},
     "emotion": "平静", "one_sentence_summary": "夜景过渡镜头"},
    {"shot_index": 29, "start_time": 29.0, "end_time": 30.0, "has_face": True,
     "content": {"main_subject": "夜景俯瞰，有人物", "people_count": 1, "people_description": "人物", "scene_type": "观景台", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "medium_long", "composition": "人物+城市", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "persona_expression", "confidence": 0.7, "reasoning": "人物+夜景，增加人格感"},
     "emotion": "温馨", "one_sentence_summary": "人物夜景合影"},
    {"shot_index": 30, "start_time": 30.0, "end_time": 31.0, "has_face": False,
     "content": {"main_subject": "城市夜景大全景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景灯光璀璨", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "大全景俯瞰", "camera_movement": "航拍/俯拍", "visual_quality": "高清，灯光璀璨"},
     "structure_role": {"primary_function": "closing_moment", "confidence": 0.85, "reasoning": "大全景夜景收尾，给观众一个震撼的收束感"},
     "emotion": "震撼", "one_sentence_summary": "重庆夜景大全景航拍，震撼收尾"},
    {"shot_index": 31, "start_time": 31.0, "end_time": 32.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "closing_moment", "confidence": 0.8, "reasoning": "延续夜景收尾氛围"},
     "emotion": "震撼", "one_sentence_summary": "夜景延续收尾"},
    {"shot_index": 32, "start_time": 32.0, "end_time": 33.0, "has_face": False,
     "content": {"main_subject": "城市夜景", "people_count": 0, "people_description": "", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "全景", "camera_movement": "固定", "visual_quality": "高清"},
     "structure_role": {"primary_function": "closing_moment", "confidence": 0.8, "reasoning": "夜景收尾"},
     "emotion": "震撼", "one_sentence_summary": "夜景收尾"},
    {"shot_index": 33, "start_time": 33.0, "end_time": 33.13, "has_face": True,
     "content": {"main_subject": "夜景大全景", "people_count": 1, "people_description": "隐约人物", "scene_type": "城市夜景", "indoor_outdoor": "outdoor", "color_temperature": "cool", "light_quality": "夜景灯光璀璨", "has_text_in_frame": False, "text_content": ""},
     "technique": {"shot_size": "long", "composition": "大全景", "camera_movement": "固定", "visual_quality": "高清，璀璨夜景"},
     "structure_role": {"primary_function": "closing_moment", "confidence": 0.9, "reasoning": "最后一帧夜景大全景，完美收束"},
     "emotion": "震撼", "one_sentence_summary": "最终夜景大全景定格"},
]

structure_analysis = {
    "script_structure": [
        {"index": 0, "purpose": "hook", "shot_range": "镜头1 - 镜头3", "content_summary": "机场手持车票，出发期待感", "duration_hint": 3, "emotion": "期待", "rhythm": "中"},
        {"index": 1, "purpose": "场景铺展", "shot_range": "镜头4 - 镜头6", "content_summary": "到达重庆，四月重庆文字卡定调", "duration_hint": 3, "emotion": "期待", "rhythm": "中"},
        {"index": 2, "purpose": "场景铺展", "shot_range": "镜头7 - 镜头16", "content_summary": "黄色出租车、商业街、城市街景，展示重庆城市风貌", "duration_hint": 10, "emotion": "活力", "rhythm": "快"},
        {"index": 3, "purpose": "情绪递进", "shot_range": "镜头17 - 镜头19", "content_summary": "夜景初现，观景台人物剪影，情绪开始升温", "duration_hint": 3, "emotion": "温馨", "rhythm": "慢"},
        {"index": 4, "purpose": "高潮爆发", "shot_range": "镜头20 - 镜头24", "content_summary": "洪崖洞夜景+长江索道+人物剪影，视觉和情绪顶点", "duration_hint": 5, "emotion": "震撼", "rhythm": "中"},
        {"index": 5, "purpose": "价值输出", "shot_range": "镜头25 - 镜头29", "content_summary": "夜景大全景过渡，情绪回落沉淀", "duration_hint": 5, "emotion": "平静", "rhythm": "慢"},
        {"index": 6, "purpose": "收尾定格", "shot_range": "镜头30 - 镜头34", "content_summary": "夜景航拍大全景收尾，震撼收束", "duration_hint": 4, "emotion": "震撼", "rhythm": "慢"},
    ],
    "rhythm_analysis": {
        "curve_points": [
            {"time": 0.0, "intensity": 0.6, "note": "出发期待，中等节奏"},
            {"time": 3.0, "intensity": 0.5, "note": "文字卡定调，节奏稍缓"},
            {"time": 6.0, "intensity": 0.7, "note": "黄色出租车视觉符号，节奏加快"},
            {"time": 10.0, "intensity": 0.8, "note": "商业街人流，快节奏铺展"},
            {"time": 16.0, "intensity": 0.5, "note": "夜景初现，节奏放缓过渡"},
            {"time": 18.0, "intensity": 0.95, "note": "观景台剪影，情绪高点"},
            {"time": 20.0, "intensity": 1.0, "note": "洪崖洞夜景，视觉最强冲击"},
            {"time": 23.0, "intensity": 0.85, "note": "索道+人物，高潮延续"},
            {"time": 28.0, "intensity": 0.5, "note": "夜景空镜，情绪沉淀"},
            {"time": 31.0, "intensity": 0.9, "note": "大全景收尾，情绪回升收束"},
        ],
        "pattern": "中-快-慢-爆发-回落-收束",
        "climax_position_percent": 60,
        "front_3s_shot_count": 3,
        "estimated_bpm_range": "90-110",
        "bgm_style_guess": "轻快电子/旅行感纯音乐，前段轻快后段抒情"
    },
    "packaging_analysis": {
        "subtitle_font_guess": "粗体无衬线字体",
        "subtitle_color_and_stroke": "白色字体+黑色描边",
        "subtitle_position": "bottom",
        "subtitle_animation": "none",
        "subtitle_density": "每秒约0字（无明显字幕）",
        "title_cards": [
            {"position_in_timeline": "大概在5秒处", "content": "四月 重庆", "style": "大字白色粗体，画面中央叠加"}
        ],
        "transitions_used": [
            {"between": "镜头间", "type": "硬切"}
        ],
        "color_grade": "natural",
        "color_grade_detail": "白天自然色调，夜景保留金黄色暖调灯光和蓝紫色冷调天空的对比",
        "stickers_effects": "无明显贴纸特效"
    },
    "hook_strategy": {
        "method": "直接展示结果",
        "detail": "以手持车票+机场环境作为开场，用即将出发的期待感抓住观众，同时车票信息暗示目的地",
        "effectiveness": "效果良好，旅行Vlog用出发场景hook是经典且有效的做法，建立期待感",
        "connection_to_body": "hook和主体衔接自然，从出发到达游玩夜景，叙事线完整"
    },
    "structure_type": {
        "category": "情绪递进型",
        "reasoning": "视频从白天的期待/活力情绪，逐步过渡到夜晚的温馨/震撼情绪，有明显的情绪递进曲线",
        "core_characteristics": "以时间和光线变化为暗线，白天铺展到黄昏过渡到夜景高潮，情绪随天色逐渐升高"
    },
    "key_techniques": [
        "城市符号植入：用黄色出租车和洪崖洞等强辨识度的城市符号快速建立地点认知",
        "文字卡点：四月重庆大字文字卡在恰当时机出现定调",
        "剪影框架构图：观景台用框架构图+人物剪影营造氛围感",
        "硬切快节奏：每秒一个镜头的硬切保持Vlog的轻快节奏",
        "日夜情绪对比：白天活力到夜景震撼的光线情绪对比",
        "第一人称视角：手持视角增强代入感和真实感"
    ],
    "narrative_type": "timeline",
    "persona_type": "back_figure",
    "persona_ratio": 0.2,
    "empty_shot_count": 20,
    "overall_emotion": "震撼",
    "overall_summary": "一支结构完整的重庆旅行Vlog，以时间线推进，从白天城市风貌到夜景情绪高潮，用标志性城市符号和观景台剪影打造记忆点"
}

from pathlib import Path
Path("data/output").mkdir(parents=True, exist_ok=True)
with open("data/output/claude_shot_analyses.json", "w", encoding="utf-8") as f:
    json.dump(shot_analyses, f, ensure_ascii=False, indent=2)
with open("data/output/claude_structure_analysis.json", "w", encoding="utf-8") as f:
    json.dump(structure_analysis, f, ensure_ascii=False, indent=2)
print("JSON saved")
